// GENERATED by tools/build-sw.mjs — do not edit. Offline play: every file of the game is cached at the first visit.
const VERSION = 'wp26-cb8322c88df5';
const FILES = [ "WaterPolo26Mobile/Assets/_Project/Resources/Localization/de.txt", "WaterPolo26Mobile/Assets/_Project/Resources/Localization/en.txt", "WaterPolo26Mobile/Assets/_Project/Resources/Localization/es.txt", "WaterPolo26Mobile/Assets/_Project/Resources/Localization/fr.txt", "WaterPolo26Mobile/Assets/_Project/Resources/Localization/it.txt", "WaterPolo26Mobile/Assets/_Project/Resources/Localization/pt.txt", "index.html", "web/assets/anim/treading.json", "web/assets/body/body.bin", "web/assets/body/body.json", "web/assets/fonts/barlow-condensed-latin-500-normal.woff2", "web/assets/fonts/barlow-condensed-latin-600-normal.woff2", "web/assets/fonts/barlow-condensed-latin-800-normal.woff2", "web/assets/head/head.bin", "web/assets/head/skin_col.jpg", "web/assets/head/skin_nrm.jpg", "web/assets/head/skin_rgh.jpg", "web/assets/icon-192.png", "web/assets/icon-512.png", "web/assets/logo.webp", "web/data/adapt.js", "web/data/clubs.js", "web/data/world.js", "web/game.js", "web/manifest.webmanifest", "web/render/arena.js", "web/render/athlete.js", "web/render/audio.js", "web/render/quality.js", "web/render/vfx.js", "web/render/water.js", "web/sim.js", "web/state.js", "web/style.css", "web/ui/app.js", "web/ui/art.js", "web/ui/i18n.js", "web/ui/ui.css", "web/vendor/three.LICENSE", "web/vendor/three.module.min.js", "web/world.js" ];
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(FILES.map((f) => new Request(f, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('wp26-') && k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
// Cache first (the game works without network); the page itself ignores the query string (?showcase...).
self.addEventListener('fetch', (e) => {
  const r = e.request; if (r.method !== 'GET' || new URL(r.url).origin !== location.origin) return;
  e.respondWith(caches.open(VERSION).then((c) => c.match(r, { ignoreSearch: r.mode === 'navigate' }).then((hit) => hit || fetch(r).then((res) => {
    if (res.ok && res.type === 'basic') c.put(r, res.clone());
    return res;
  }).catch(() => (r.mode === 'navigate' ? c.match('index.html') : Response.error())))));
});
