// Run: node tools/build-sw.mjs — writes sw.js (offline play): the list of every file the game loads and a
// version = hash of their contents, so a changed file installs a new cache. `--check` fails if sw.js is stale.
import fs from 'fs'; import path from 'path'; import crypto from 'crypto';
const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const walk = (d) => fs.readdirSync(path.join(root, d), { withFileTypes: true }).flatMap((e) => (e.isDirectory() ? walk(path.join(d, e.name)) : [path.join(d, e.name)]));
const files = ['index.html', ...walk('web').filter((f) => !f.endsWith('.md') && !f.endsWith('.txt') && !f.endsWith('clubs.json')),
  ...walk('WaterPolo26Mobile/Assets/_Project/Resources/Localization').filter((f) => f.endsWith('.txt'))].map((f) => f.split(path.sep).join('/')).sort();
const h = crypto.createHash('sha256'); for (const f of files) h.update(f).update(fs.readFileSync(path.join(root, f)));
const version = h.digest('hex').slice(0, 12);
const out = `// GENERATED by tools/build-sw.mjs — do not edit. Offline play: every file of the game is cached at the first visit.
const VERSION = 'wp26-${version}';
const FILES = ${JSON.stringify(files, null, 1).replace(/\n\s*/g, ' ')};
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(VERSION).then((c) => c.addAll(FILES.map((f) => new Request(f, { cache: 'reload' })))).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k.startsWith('wp26-') && k !== VERSION).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});
// Cache first (the game works without network); the page itself ignores the query string (?showcase...).
self.addEventListener('fetch', (e) => {
  const r = e.request; if (r.method !== 'GET' || new URL(r.url).origin !== location.origin) return;
  e.respondWith(caches.open(VERSION).then((c) => c.match(r, { ignoreSearch: r.mode === 'navigate' }).then((hit) => hit || fetch(r).then((res) => {
    if (res.ok && res.type === 'basic') c.put(r, res.clone());
    return res;
  }).catch(() => (r.mode === 'navigate' ? c.match('index.html') : Response.error())))));
});
`;
const dst = path.join(root, 'sw.js');
if (process.argv.includes('--check')) {
  const ok = fs.existsSync(dst) && fs.readFileSync(dst, 'utf8') === out;
  console.log(ok ? `PASS sw.js up to date (${files.length} files, ${version})` : 'FAIL sw.js is stale: run node tools/build-sw.mjs'); process.exit(ok ? 0 : 1);
}
fs.writeFileSync(dst, out); console.log(`sw.js: ${files.length} files, version ${version}`);
